In [6]:
import numpy as np
import time 
import sys
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
s = range(1000)
print(sys.getsizeof(5)*len(s))
d = np.arange(1000)
print(d.size*d.itemsize)


28000
4000
